# Generated by Django 5.2.7 on 2025-10-24 05:22

import accounts.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=functools.partial(accounts.models.model_image_file_path, *(), **{'model': 'profile'})),
        ),
    ]
