# Generated by Django 5.2.7 on 2025-11-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_tag_product_product_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
