'''
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
'''


import os
import logging
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET', 'changeme')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get('DEBUG', 0)))
print(DEBUG)

ALLOWED_HOSTS = list(filter(
    None,
    os.environ.get('ALLOWED_HOSTS', '').split(',')
))

# Logger
logger = logging.getLogger(__name__)


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.auth.EmailOrUsernameBackend'
]

# Application definition
INSTALLED_APPS = [
    'wagtail_headless_preview',
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',
    'taggit',
    'modelcluster',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.postgres',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'storages',
    'corsheaders',  
    'core',
    'cart',
    'store',
    'accounts',
    'payments', 
    'home',
    'blog',
]

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    ALLOWED_HOSTS = ['*']  # for local development
    logger.setLevel(logging.DEBUG)
else: 
    EMAIL_SUBJECT_PREFIX = os.getenv('MAIL_PREFIX', '')
    EMAIL_USE_SSL = True 
    EMAIL_PORT = 465  
    EMAIL_HOST_USER = os.getenv('MAIL_USER')
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
    SERVER_EMAIL = EMAIL_HOST_USER
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('MAIL_HOST')
    EMAIL_HOST_PASSWORD = os.getenv('MAIL_PASS')
    ADMINS = [
        (NAME, EMAIL) for NAME, EMAIL in zip(
            os.getenv('ADMIN_NAMES', '').split(','),
            os.getenv('ADMIN_EMAILS', '').split(',')
        )
    ]

    if not EMAIL_HOST or not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        raise Exception('SMTP credentials are not fully defined')

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',    # Vite dev server
    'http://127.0.0.1:5173',
    'http://proxy:8000',        # Nginx
    'http://localhost:8080', 
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',    # Vite dev server
    'http://127.0.0.1:5173',
    'http://proxy:8000',        # Nginx
    'http://localhost:8080', 
]


# For APIs only:
CORS_URLS_REGEX = r'^/api/.*$'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'ninja.compatibility.files.fix_request_files_middleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.utils.context_processor.cart_context',
                'accounts.utils.context_processor.profile_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.get('DB_HOST'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.User'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Check if production environment (or another specific setting) is enabled
# For example, by using a flag in your environment variables.
USE_SPACES = os.getenv('USE_SPACES', 'False') == 'True'

if USE_SPACES:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        }
    }
    
    # Required for django-storages to connect to DigitalOcean
    AWS_S3_ENDPOINT_URL = os.environ.get('SB_ENDPOINT_URL')
    AWS_ACCESS_KEY_ID = os.environ.get('SB_KEY')
    AWS_SECRET_ACCESS_KEY = os.environ.get('SB_SECRET')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('SB_NAME')

    # Public access control list for the files
    AWS_DEFAULT_ACL = 'public-read'

    # Optional: Cache control for browser caching
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

    AWS_LOCATION = 'files' # Needed for boto3
    # Configure the URL and location for static files
    STATIC_LOCATION = 'static' # This is the folder name in your bucket
    STATIC_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/{AWS_LOCATION}/{STATIC_LOCATION}'
   
    # Configure the URL and location for media files
    MEDIA_LOCATION = 'media' # This is the folder name in your bucket
    MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/{AWS_LOCATION}/{MEDIA_LOCATION}'
    
    
else: # Local development
    STATIC_URL = os.getenv('STATIC_URL', '/files/static/')
    MEDIA_URL = os.getenv('MEDIA_URL', '/files/media/')

    STATIC_ROOT = os.getenv('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))
    MEDIA_ROOT = os.getenv('MEDIA_ROOT', os.path.join(BASE_DIR, 'mediafiles'))


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Wagtail settings
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
WAGTAIL_SITE_NAME = os.environ.get('WAGTAIL_SITE_NAME', 'My Wagtail Site')

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = os.environ.get('WAGTAILADMIN_BASE_URL', 'http://example.com')

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']