# Generated by Django 6.0 on 2026-01-16 19:37

import django.db.models.deletion
import wagtail.fields
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('stats', wagtail.fields.StreamField([('stat', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Stat name, e.g., 'Offices worldwide'", 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Stat value, e.g., '12' or '300+'", 'max_length': 100}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('value', 1)]], {})}, help_text='Add key statistics (e.g., team size, experience). Orderable via drag-and-drop.')),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
